os: linux
language: cpp
addons:
  apt:
    packages: &baseline-packages
      - valgrind

# Template some configurations for different distros, to be used in the jobs
# below
_xenial-conf: &xenial
  dist: xenial
  env: &xenial-env
    - CONFIGURE_FLAGS=--with-boost=`pwd`/cache/boost
    - DOWNLOAD_BOOST=1.64.0

_xenial-clang-env-conf:
  env: &xenial-clang-env
    - *xenial-env
    - CC=clang
    - CXX=clang++

_bionic-conf: &bionic
  dist: bionic
  addons:
    apt:
      packages: &bionic-packages
        - *baseline-packages
        - libboost-test-dev
        - libboost-system-dev

_focal-conf: &focal
  dist: focal
  addons:
    apt:
      packages:
        - *baseline-packages
        - libboost-test-dev
        - libboost-system-dev

_bionic-clang-env-conf:
  env: &bionic-clang-env
    - CC=clang
    - CXX=clang++

jobs:
  include:
    - <<: *focal
      env:
        - LLVM_VERSION=11.0.0-rc2
        - CONFIGURE_FLAGS=--disable-llvm-clang-version-check
    - <<: *bionic
      env: LLVM_VERSION=10.0.0
    - <<: *bionic
      env: LLVM_VERSION=9.0.0
    - <<: *bionic
      env: LLVM_VERSION=8.0.0
    - <<: *bionic
      env:
        - *bionic-clang-env
        - LLVM_VERSION=7.0.1
    - <<: *bionic
      addons:
        apt:
          packages:
            - *bionic-packages
            - llvm-6.0-dev
            - clang-6.0
      env: CONFIGURE_FLAGS=--with-llvm=/usr/lib/llvm-6.0/
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=5.0.2
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=4.0.0
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=3.9.1
    - <<: *xenial
      addons:
        apt:
          packages:
            - *baseline-packages
            - llvm-3.8-dev
            - clang-3.8
      env:
        - DOWNLOAD_BOOST=1.64.0
        - CONFIGURE_FLAGS="--with-llvm=/usr/lib/llvm-3.8/ --with-boost=`pwd`/cache/boost"
      compiler: clang # Not working with GCC
    - services: docker
      before_script: docker build -t nidhugg .
      script: docker run --rm -ti -v `pwd`:`pwd` -w `pwd` nidhugg nidhuggc -sc tests/smoke/C-tests/mutex_hard.c

before_script:
  - ./travis/install_deps.sh
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH="$LLVM_DIR/lib:$PWD/cache/boost/lib"
  - autoreconf --install
  - ./configure $CONFIGURE_FLAGS || (cat config.log; false)
  - make -Csrc -j6 all unittest
script:
  - make test && make valtest
cache:
  directories:
    - cache
