language: C++
sudo: false
addons:
  apt:
    packages: &baseline-packages
      - valgrind

# Template some configurations for different distros, to be used in the matrix
# below
_xenial-conf: &xenial
  dist: xenial
  env: &xenial-env
    - CONFIGURE_FLAGS=--with-boost=`pwd`/cache/boost
    - DOWNLOAD_BOOST=1.64.0

_xenial-clang-env-conf:
  env: &xenial-clang-env
    - *xenial-env
    - CC=clang
    - CXX=clang++

_bionic-conf: &bionic
  dist: bionic
  addons:
    apt:
      packages: &bionic-packages
        - *baseline-packages
        - libboost-test-dev
        - libboost-system-dev

_bionic-clang-env-conf:
  env: &bionic-clang-env
    - CC=clang
    - CXX=clang++

matrix:
  include:
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=3.8.1  # default on Debian stretch - does NOT work yet
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=3.9.1
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=4.0.0
    - <<: *xenial
      env:
        - *xenial-clang-env
        - LLVM_VERSION=5.0.2
    - <<: *bionic
      addons:
        apt:
          packages:
            - *bionic-packages
            - llvm-6.0-dev
            - clang-6.0
      env: CONFIGURE_FLAGS=--with-llvm=/usr/lib/llvm-6.0/
    - <<: *bionic
      env:
        - *bionic-clang-env
        - LLVM_VERSION=7.0.1
    - <<: *bionic
      env: LLVM_VERSION=8.0.0

before_script:
  - ./travis/install_deps.sh
  - export LLVM_DIR=$PWD/cache/clang+llvm-$LLVM_VERSION
  - export PATH=$LLVM_DIR/bin:$PATH
  - export LD_LIBRARY_PATH="$LLVM_DIR/lib:$PWD/cache/boost/lib"
  - autoreconf --install
  - ./configure CXXFLAGS="-I"`pwd`"/deps/immer/" $CONFIGURE_FLAGS || (cat config.log; false)
  - make -Csrc -j6 all unittest
script:
  - make test && make valtest
cache:
  directories:
    - cache
